font_size 13.5
disable_ligatures never

# cursor #cccccc

cursor_shape beam 

copy_on_select yes
clear_selection_on_clipboard_loss yes
remember_window_size  yes

background_opacity 0.95

# BEGIN_KITTY_THEME
# 3024 Night
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="GoogleSansCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Força o Kitty a buscar os ícones do Starship diretamente na fonte de símbolos
symbol_map U+E5FA-U+E62B,U+E700-U+E7C5,U+F000-U+F2E0,U+E200-U+E2A9,U+F400-U+F4A8,U+F300-U+F313,U+E0A0-U+E0A2,U+E0B0-U+E0B3,U+E0A3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+2665,U+26A1,U+F27C,U+F300-U+F32D,U+E5FA-U+E6B1,U+F0001-U+F1AF0 Symbols Nerd Font

